# Upstream ships a single static Go binary in the release tarball — the
# completions are generated from the binary itself at install time; the man
# page and license come from the tag tarball (Source1).
%define debug_package %{nil}
%global _build_id_links none

Name:           fzf
Version:        0.74.4
Release:        1%{?dist}
Summary:        A command-line fuzzy finder

License:        MIT
URL:            https://github.com/junegunn/fzf
Source0:        %{url}/releases/download/v%{version}/fzf-%{version}-linux_amd64.tar.gz
Source1:        %{url}/archive/refs/tags/v%{version}.tar.gz
#!RemoteAsset
ExclusiveArch:  x86_64

Requires:       bash

%description
fzf is a general-purpose command-line fuzzy finder with an interactive
filter and preview: it applies fuzzy matching to any list of lines — files,
command history, processes, hostnames, bookmarks, git commits — and is
scriptable from shells and editors.

%prep
# Source0 (single binary) unpacks into the created top dir; the tag tree
# (Source1, man page + license + readme) is extracted manually — the setup
# family of macros never unpacks extra sources — flattened onto it
%autosetup -n fzf-%{version} -c
tar -xzf %{_sourcedir}/v%{version}.tar.gz --strip-components=1

%build
# static Go binary shipped by upstream

%install
install -Dpm0755 fzf %{buildroot}%{_bindir}/fzf
# shell completions generated by the binary itself (upstream's documented
# mechanism — the release tarball carries no shell/ tree)
./fzf --bash > fzf.bash
./fzf --zsh > _fzf
./fzf --fish > fzf.fish
install -Dpm0644 fzf.bash %{buildroot}%{_datadir}/bash-completion/completions/fzf
install -Dpm0644 _fzf %{buildroot}%{_datadir}/zsh/site-functions/_fzf
install -Dpm0644 fzf.fish %{buildroot}%{_datadir}/fish/vendor_completions.d/fzf.fish
# man page + license + docs from the tag tree (flattened into the top dir)
install -Dpm0644 man/man1/fzf.1 %{buildroot}%{_mandir}/man1/fzf.1
install -Dpm0644 LICENSE %{buildroot}%{_licensedir}/%{name}/LICENSE
install -Dpm0644 README.md %{buildroot}%{_docdir}/%{name}/README.md

%files
%license %{_licensedir}/%{name}/LICENSE
%doc %{_docdir}/%{name}/README.md
%{_bindir}/fzf
%{_mandir}/man1/fzf.1*
%{_datadir}/bash-completion/completions/fzf
%{_datadir}/zsh/site-functions/_fzf
%{_datadir}/fish/vendor_completions.d/fzf.fish

%changelog
* Sat Sep 26 2026 halcyon-autoupdate <aahsnr041@proton.me> - 0.74.4-1
- initial packaging (release-binary wrapper; shadows Fedora's identical
  version so updates land here first)
