# Wrapper over uv's official prebuilt musl release tarball (contains the uv
# and uvx executables). Shell completions are generated by running the
# binary at build time — the static musl binary runs anywhere.
Name:           uv
Version:        0.12.21
Release:        1%{?dist}
Summary:        An extremely fast Python package and project manager, written in Rust
License:        MIT OR Apache-2.0
URL:            https://docs.astral.sh/uv/
#!RemoteAsset
Source0:        https://github.com/astral-sh/uv/releases/download/%{version}/uv-x86_64-unknown-linux-musl.tar.gz
#!RemoteAsset
Source1:        https://raw.githubusercontent.com/astral-sh/uv/%{version}/LICENSE-APACHE
#!RemoteAsset
Source2:        https://raw.githubusercontent.com/astral-sh/uv/%{version}/LICENSE-MIT

ExclusiveArch:  x86_64

# prebuilt foreign binary: nothing to produce debug symbols from
%define debug_package %{nil}
%global _build_id_links none

%description
uv is an extremely fast Python package and project manager, written in Rust:
a drop-in replacement for pip/pip-tools/virtualenv/pipx and more.

%prep
%autosetup -n uv-x86_64-unknown-linux-musl

%install
# vendor tarballs ship no license text; the repo LICENSE rides along
install -Dpm0644 %{SOURCE1} %{buildroot}%{_licensedir}/%{name}/LICENSE-APACHE
install -Dpm0644 %{SOURCE2} %{buildroot}%{_licensedir}/%{name}/LICENSE-MIT
install -Dpm755 uv %{buildroot}%{_bindir}/uv
install -Dpm755 uvx %{buildroot}%{_bindir}/uvx
# completions come from the clap_complete flag on each binary — the
# generate-shell-completions subcommand was removed upstream after 0.12.17
for cmd in uv uvx; do
    ./$cmd --generate-shell-completion bash > $cmd.bash
    ./$cmd --generate-shell-completion zsh  > _$cmd
    ./$cmd --generate-shell-completion fish > $cmd.fish
done
install -Dpm644 uv.bash  %{buildroot}%{_datadir}/bash-completion/completions/uv
install -Dpm644 _uv      %{buildroot}%{_datadir}/zsh/site-functions/_uv
install -Dpm644 uv.fish  %{buildroot}%{_datadir}/fish/vendor_completions.d/uv.fish
install -Dpm644 uvx.bash %{buildroot}%{_datadir}/bash-completion/completions/uvx
install -Dpm644 _uvx     %{buildroot}%{_datadir}/zsh/site-functions/_uvx
install -Dpm644 uvx.fish %{buildroot}%{_datadir}/fish/vendor_completions.d/uvx.fish

%files
%license LICENSE-APACHE
%license LICENSE-MIT
%{_bindir}/uv
%{_bindir}/uvx
%{_datadir}/bash-completion/completions/uv
%{_datadir}/zsh/site-functions/_uv
%{_datadir}/fish/vendor_completions.d/uv.fish
%{_datadir}/bash-completion/completions/uvx
%{_datadir}/zsh/site-functions/_uvx
%{_datadir}/fish/vendor_completions.d/uvx.fish

%changelog
* Fri Sep 25 2026 halcyon-autobump <aahsnr041@proton.me>
- back to the wrapper over the official musl release tarball (was: rust
  source build with the terra cargo macro set)
